SELECT 
Company.CompanyID as V_CompanyID,
Company.name AS V_CompanyName,
Company.clientcode AS V_CompanyClientCode,
Company.town AS V_CompanyTown,
Company.county AS V_CompanyCounty,
Company.country AS V_CompanyCountry,
Company.postcode AS V_CompanyPostcode,
(SELECT name FROM pears.companystatus WHERE companystatusid = company.status ) AS V_CompanyStatus,
(SELECT descrip FROM pears.vacancyclass WHERE classcode = company.source ) AS V_CompanySource,
(SELECT name FROM pears.division WHERE divisionid = company.divisionid ) AS V_CompanyDivision,
CPerson.name AS V_CompanyPersonName,
Person.PersonID as V_PersonID,
Person.name AS V_PersonName,
Person.town AS V_PersonTown,
Person.county AS V_PersonCounty,
Person.country AS V_PersonCountry,
Person.postcode AS V_PersonPostcode,
Person.PayrollNumber as V_PersonPayrollNumber,
Person.Forenames as V_PersonForenames,
Person.Surname as V_PersonSurname,
Person.Appnumber as V_PersonRegistrationNumber,
Person.registrationdate as V_PersonRegistrationDate,
(SELECT name FROM pears.status WHERE status = person.status AND status.type = 'P' ) AS V_PersonStatus,
contactevent.contacteventid as V_ContactID,
contactevent.ContactDate as V_ContactDate,
(SELECT classdescrip FROM pears.contactclass WHERE classcode = contactevent.classcode) AS V_ContactClass,
contactevent.outcome as V_ContactOutcome,
(select userid from pears.staff where staffid=contactevent.staffid) as V_ContactConsultant,
contactevent.description as V_ContactDescription,
(if contactevent.who in ('A','B') then 1 else 0 endif) as V_ToPerson,
(if contactevent.who in ('C','B') then 1 else 0 endif) as V_ToCompany
FROM 
pears.contactevent key left outer join (pears.employment KEY JOIN ( pears.Company , pears.Person as CPerson )),
pears.contactevent key left outer join pears.person
