SELECT 
company.CompanyID as L_CompanyID,
Company.name AS L_CompanyName,
Company.clientcode AS L_CompanyClientCode,
Company.town AS L_CompanyTown,
Company.county AS L_CompanyCounty,
Company.country AS L_CompanyCountry,
Company.postcode AS L_CompanyPostcode,
(SELECT name FROM pears.companystatus WHERE companystatusid = company.status ) AS L_CompanyStatus,
(SELECT descrip FROM pears.vacancyclass WHERE classcode = company.source ) AS L_CompanySource,
(SELECT name FROM pears.division WHERE divisionid = company.divisionid ) AS L_CompanyDivision,
employment.StartDate as L_PlacementStartDate,
employment.LeaveDate as L_PlacementEndDate,
employment.Position as L_PlacementPosition,
Placement.TheirRef as L_PlacementTheirRef,
isnull(Employment.temp,0) as L_PlacementTemp,
(if L_PlacementTemp=0 then 1 else 0 endif) as L_PlacementPerm,
Placement.PlacementID as L_PlacementID,
Placement.salary as L_PlacementSalary,
(select userid from pears.staff where staffid=placement.staffid) as L_PlacementConsultant,
person.PersonID as L_PersonID,
Person.name AS L_PersonName,
Person.town AS L_PersonTown,
Person.county AS L_PersonCounty,
Person.country AS L_PersonCountry,
Person.postcode AS L_PersonPostcode,
Person.PayrollNumber as L_PersonPayrollNumber,
Person.Forenames as L_PersonForenames,
Person.Surname as L_PersonSurname,
Person.Appnumber as L_PersonRegistrationNumber,
Person.registrationdate as L_PersonRegistrationDate,
(SELECT name FROM pears.status WHERE status = person.status AND status.type = 'P' ) AS L_PersonStatus,
(select userid from pears.staff where staffid=person.staffid) as L_PersonConsultant
FROM pears.Placement KEY JOIN pears.employment KEY JOIN ( pears.Company , pears.Person )
