SELECT 
company.CompanyID as R_CompanyID,
Company.name AS R_CompanyName,
Company.clientcode AS R_CompanyClientCode,
Company.town AS R_CompanyTown,
Company.county AS R_CompanyCounty,
Company.country AS R_CompanyCountry,
Company.postcode AS R_CompanyPostcode,
(SELECT name FROM pears.companystatus WHERE companystatusid = company.status ) AS R_CompanyStatus,
(SELECT descrip FROM pears.vacancyclass WHERE classcode = company.source ) AS R_CompanySource,
(SELECT name FROM pears.division WHERE divisionid = company.divisionid ) AS R_CompanyDivision,
CPerson.name AS R_CompanyPersonName,
person.PersonID as R_PersonID,
Person.name AS R_PersonName,
Person.town AS R_PersonTown,
Person.county AS R_PersonCounty,
Person.country AS R_PersonCountry,
Person.postcode AS R_PersonPostcode,
Person.PayrollNumber as R_PersonPayrollNumber,
Person.Forenames as R_PersonForenames,
Person.Surname as R_PersonSurname,
Person.Appnumber as R_PersonRegistrationNumber,
Person.registrationdate as R_PersonRegistrationDate,
(SELECT name FROM pears.status WHERE status = person.status AND status.type = 'P' ) AS R_PersonStatus,
(select userid from pears.staff where staffid=person.staffid) as R_PersonConsultant,
vacancy.VacancyID as R_VacancyID,
vacancy.StartDate as R_VacancyStartDate,
vacancy.FinishDate as R_VacancyEndDate,
Vacancy.Position as R_VacancyPosition,
Vacancy.TheirRef as R_VacancyTheirRef,
isnull(Vacancy.temp,0) as R_VacancyTemp,
(if R_VacancyTemp=0 then 1 else 0 endif) as R_VacancyPerm,
(select userid from pears.staff where staffid=Vacancy.staffid) as R_VacancyConsultant,
(SELECT name FROM pears.status WHERE status = vacancy.status AND status.type = 'V' ) AS R_VacancyStatus,
progress.ProgressID as R_ProgressID,
(SELECT name FROM pears.status WHERE status = progress.status AND status.type = 'R' ) AS R_ProgressStatus,
progress.actiondate as R_ProgressActionDate
FROM pears.progress KEY JOIN (pears.person,(pears.vacancy key join pears.employment KEY JOIN ( pears.Company , pears.Person as CPerson )))
