SELECT 
Company.CompanyID as T_CompanyID,
Company.name AS T_CompanyName,
Company.clientcode AS T_CompanyClientCode,
Company.town AS T_CompanyTown,
Company.county AS T_CompanyCounty,
Company.country AS T_CompanyCountry,
Company.postcode AS T_CompanyPostcode,
(SELECT name FROM pears.companystatus WHERE companystatusid = company.status ) AS T_CompanyStatus,
(SELECT descrip FROM pears.vacancyclass WHERE classcode = company.source ) AS T_CompanySource,
(SELECT name FROM pears.division WHERE divisionid = company.divisionid ) AS T_CompanyDivision,
employment.StartDate as T_PlacementStartDate,
employment.LeaveDate as T_PlacementEndDate,
employment.Position as T_PlacementPosition,
Placement.TheirRef as T_PlacementTheirRef,
(select userid from pears.staff where staffid=placement.staffid) as T_PlacementConsultant,
Person.personid as T_PersonID,
Person.name AS T_PersonName,
Person.town AS T_PersonTown,
Person.county AS T_PersonCounty,
Person.country AS T_PersonCountry,
Person.postcode AS T_PersonPostcode,
Person.PayrollNumber as T_PersonPayrollNumber,
Person.Forenames as T_PersonForenames,
Person.Surname as T_PersonSurname,
Person.Appnumber as T_PersonRegistrationNumber,
Person.registrationdate as T_PersonRegistrationDate,
(SELECT name FROM pears.status WHERE status = person.status AND status.type = 'P' ) AS T_PersonStatus,
(select userid from pears.staff where staffid=person.staffid) as T_PersonConsultant,
TempTimeSheet.SerialNumber as T_TimesheetNumber,
TempTimeSheet.Period as T_TimesheetPeriod,
TempTimeSheet.PeriodLength as T_TimesheetPeriodLength,
TempTimeSheet.PayrollIdentifier as T_TimesheetPayrollCompany,
TempTimeSheet.AnalysisCode as T_TimesheetAnalysisCode,
TempTimeSheet.TheirRef as T_TimesheetTheirRef,
TempTimeSheetLine.LineNumber as T_LineNumber,
TempTimeSheetLine.UnitsPaid as T_UnitsPaid,
TempTimeSheetLine.PayRate as T_PayRate,
TempTimeSheetLine.UnitsCharged as T_UnitsCharged,
TempTimeSheetLine.ChargeRate as T_ChargeRate
FROM pears.TempTimeSheetLine KEY JOIN pears.TempTimeSheet KEY JOIN pears.Placement KEY JOIN pears.employment KEY JOIN ( pears.Company , pears.Person )
